
import java.awt.Image;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.Timer;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dergi
 */
public final class Pv extends javax.swing.JFrame {
    private boolean isPanelVisible = false;  // Estado del panel (visible o no)
    private Timer temporizador;
    private boolean isAnimating = false;

    private int panelPosicionX = -92;  // Posición inicial del panel
    private final int panelMaxX = 1;  // Posición final del panel cuando está visible
    private final int panelMinX = -90;  // Posición final del panel cuando está oculto
    int cont=0;

    /**
     * Creates new form Pv
     */
    public Pv() {
        initComponents();
        this.setLocationRelativeTo(null);
        masc();
        buscar();
        buscarc ();
        ec();
    }
    private void ocultarPanel() {
        // Animar el panel para ocultarlo
        temporizador = new Timer(4, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (panelPosicionX > panelMinX) {
                    panelPosicionX -= 8; //PIxel por ms
                    p.setLocation(panelPosicionX, p.getY());
                } else {
                    temporizador.stop();
                    isPanelVisible = false;  // Panel oculto
                }
            }
        });
        cont=0;
        temporizador.start();  // Iniciar la animación
    }

    private void mostrarPanel() {
        // Animar el panel para mostrarlo
        temporizador = new Timer(4, new ActionListener() {
            public void actionPerformed(ActionEvent e) {
                if (panelPosicionX < panelMaxX) {
                    panelPosicionX += 8; //Pixel por ms
                    p.setLocation(panelPosicionX, p.getY());
                } else {
                    temporizador.stop();
                    isPanelVisible = true;  // Panel visible
                }
            }
        });
        temporizador.start();  // Iniciar la animación
    }

    public void gif_buscar (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/buscar.gif"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        buscar.setIcon(gif); 
    }
    public void buscar (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/buscar.png"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        buscar.setIcon(gif); 
    }
    
    public void gif_cobrar (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/icons8-bolsa-de-dinero.gif"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        cobrar.setIcon(gif); 
    }
    
     public void gif_masc (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/agregar.gif"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        mascliente.setIcon(gif); 
    }
     public void masc (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/agregar.png"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50,50, Image.SCALE_DEFAULT));
        mascliente.setIcon(gif); 
    }
     public void gif_buscarc (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/buscaru.gif"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        buscarc.setIcon(gif); 
    }
     public void buscarc (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/buscaru.png"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        buscarc.setIcon(gif); 
    }   
     public void gif_ec (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/eliminar-usuario.gif"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        elimc.setIcon(gif); 
    }
     public void ec (){
        ImageIcon i = new ImageIcon(getClass().getResource("/imagenes/eliminar-usuario.png"));
        Icon gif = new ImageIcon (i.getImage().getScaledInstance(50, 50, Image.SCALE_DEFAULT));
        elimc.setIcon(gif); 
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        p = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        mascliente = new javax.swing.JLabel();
        buscar = new javax.swing.JLabel();
        buscarc = new javax.swing.JLabel();
        elimc = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cobrar = new javax.swing.JButton();
        jPanel7 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel9 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(226, 241, 231));
        jPanel1.setLayout(null);

        p.setBackground(new java.awt.Color(36, 54, 66));
        p.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                pMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                pMouseExited(evt);
            }
        });
        p.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("jButton1");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jButton1MouseEntered(evt);
            }
        });
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        p.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 70, 60, 60));

        jButton2.setText("jButton2");
        p.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 280, 60, 60));

        jButton3.setText("jButton2");
        p.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 140, 60, 60));

        jButton4.setText("jButton2");
        p.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 210, 60, 60));

        jPanel1.add(p);
        p.setBounds(-90, 50, 160, 680);

        jPanel3.setBackground(new java.awt.Color(36, 54, 66));

        jLabel7.setFont(new java.awt.Font("Georgia", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Administrador");

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/icono perfil.png"))); // NOI18N
        jLabel3.setText("jLabel3");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(932, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(1, 1, 1)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel3))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel3);
        jPanel3.setBounds(-10, 0, 1160, 50);

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        mascliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                masclienteMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                masclienteMouseExited(evt);
            }
        });

        buscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarMouseExited(evt);
            }
        });

        buscarc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                buscarcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                buscarcMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buscarcMousePressed(evt);
            }
        });

        elimc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                elimcMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                elimcMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                elimcMousePressed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addComponent(mascliente, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(elimc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addComponent(buscarc, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(510, 510, 510)
                .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mascliente, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(elimc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buscarc, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 60));

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("GANANCIA");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 120, 30));

        jPanel4.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 90, 980, 30));

        cobrar.setBackground(new java.awt.Color(56, 116, 120));
        cobrar.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        cobrar.setForeground(new java.awt.Color(255, 255, 255));
        cobrar.setText("Cobrar");
        cobrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                cobrarMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                cobrarMouseExited(evt);
            }
        });
        jPanel4.add(cobrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(980, 0, 100, 120));

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("TOTAL ");
        jLabel4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jPanel7.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 110, 20));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 980, 30));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(70, 610, 1080, 120);

        jPanel8.setBackground(new java.awt.Color(226, 241, 231));
        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Carrito");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Catidad", "Codigo", "Producto", "Precio"
            }
        ));
        jScrollPane3.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 762, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3)
                .addContainerGap())
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel8);
        jPanel8.setBounds(70, 50, 770, 560);

        jPanel9.setBackground(new java.awt.Color(226, 241, 231));
        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Georgia", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Categorias");

        jList1.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jScrollPane1)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 534, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel9);
        jPanel9.setBounds(840, 50, 310, 560);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-1, 0, 1160, 734));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cobrarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cobrarMouseEntered
        // TODO add your handling code here:
       cobrar.setText("");
        gif_cobrar(); 
    }//GEN-LAST:event_cobrarMouseEntered

    private void cobrarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cobrarMouseExited
        cobrar.setIcon(null);
        cobrar.setText("Cobrar");
    }//GEN-LAST:event_cobrarMouseExited

    private void masclienteMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masclienteMouseEntered
        // TODO add your handling code here:
        gif_masc();
    }//GEN-LAST:event_masclienteMouseEntered

    private void masclienteMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_masclienteMouseExited
        // TODO add your handling code here:
        masc();
    }//GEN-LAST:event_masclienteMouseExited

    private void buscarMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseEntered
        // TODO add your handling code here:
        gif_buscar();
    }//GEN-LAST:event_buscarMouseEntered

    private void buscarMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarMouseExited
        // TODO add your handling code here:
        buscar();
    }//GEN-LAST:event_buscarMouseExited

    private void buscarcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarcMouseExited
        // TODO add your handling code here:
        buscarc();
    }//GEN-LAST:event_buscarcMouseExited

    private void buscarcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarcMousePressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_buscarcMousePressed

    private void buscarcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buscarcMouseEntered
        // TODO add your handling code here:
        gif_buscarc();
    }//GEN-LAST:event_buscarcMouseEntered

    private void elimcMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimcMouseEntered
        // TODO add your handling code here:
        gif_ec();
    }//GEN-LAST:event_elimcMouseEntered

    private void elimcMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimcMouseExited
        // TODO add your handling code here:
        ec();
    }//GEN-LAST:event_elimcMouseExited

    private void elimcMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_elimcMousePressed
        // TODO add your handling code here:
    }//GEN-LAST:event_elimcMousePressed

    private void pMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseEntered

    if (isPanelVisible ) {
                ocultarPanel(); // Llamar al método para ocultar el panel
            } else {
                mostrarPanel(); // Llamar al método para mostrar el panel
              }
    }//GEN-LAST:event_pMouseEntered

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        Produc i = new Produc();
        i.setVisible(true);
        ocultarPanel();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void pMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_pMouseExited

    private void jButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseEntered
        // TODO add your handling code here:

    }//GEN-LAST:event_jButton1MouseEntered

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pv.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pv().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buscar;
    private javax.swing.JLabel buscarc;
    private javax.swing.JButton cobrar;
    private javax.swing.JLabel elimc;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel mascliente;
    private javax.swing.JPanel p;
    // End of variables declaration//GEN-END:variables
}
